### ISSUE TITLE
Do I need to install the Xcode app to run the tool?

### ISSUE THREAD

**Issue by RichardJTownsend** [fgimian/cubase-project-plugins#1]
Hi fgimian,

I'm about to migrate to a new computer and I thought your tool would be perfect for helping me to do housekeeping on unused plugins. I ran the install command for your executable, and mid-way through, it asked if I wanted to install the Xcode developers tools.

I wasn't sure, so I said no.

Do I need them for the tool to run successfully?

Many thanks

Rich

**Comment by fgimian** [comment]
> Hi fgimian,
> 
> I'm about to migrate to a new computer and I thought your tool would be perfect for helping me to do housekeeping on unused plugins. I ran the install command for your executable, and mid-way through, it asked if I wanted to install the Xcode developers tools.
> 
> I wasn't sure, so I said no.
> 
> Do I need them for the tool to run successfully?
> 
> Many thanks
> 
> Rich

Hey Rich, I haven't actually built this tool on macOS before and wouldn't have expected the Xcode tools to be required to be honest.

I would install [Homebrew](https://brew.sh/), then use that to install Go via `brew install go` and then you should be able to build the tool. If doing so prompts you to install Xcode Command Line Tools, then I suppose it may be needed for macOS.

I may look at providing pre-built binaries for future mate.

Cheers
Fotis

**Comment by RichardJTownsend** [comment]
Thanks very much Fotis!

**Comment by fgimian** [comment]
I've now setup GoReleaser and GitHub Actions to publish builds for macOS, Linux and Windows on each release. You can grab the latest release v1.1.0 at https://github.com/fgimian/cubase-project-plugins/releases.

I do not sign releases and have no easy way to test them on macOS so hopefully they work as expected.

I'll close this issue as completed now that this is done 😄 

Cheers
Fotis
